// Only local copy is printed: API messages, URLs and detail fields are untrusted.
// Keep this lightweight catalog shared by every CLI command. Load it only on
// failure so operation search and successful requests pay no catalog cost.
const apiErrorMessages: Readonly<Record<string, string>> = {
  idempotency_key_invalid: "Provide a valid, bounded --idempotency-key value.",
  idempotency_key_reused: "This idempotency key was used with a different request body. Check the earlier result; use a new key only for a new action.",
  idempotency_key_in_progress: "This request is still being processed. Wait, then retry the same request with the same idempotency key.",
  invalid_analytics_query: "Check the analytics report fields against the operation's input schema.",
  invalid_date_range: "Choose a valid start and end date for the report.",
  analytics_range_too_large: "Choose a shorter date range for the report.",
  invalid_analytics_grouping: "Choose a grouping supported by this analytics report.",
  provider_grouping_requires_broadcast_sources: "Include Broadcast sources when grouping an analytics report by provider.",
  broadcast_not_sendable: "Check the Broadcast's status and run its send preflight before starting delivery.",
  broadcast_connection_unavailable: "Choose an available email delivery connection and run the Broadcast preflight again.",
  broadcast_no_recipients: "Review the Broadcast's Subscriber selection. It currently has no eligible recipients.",
  broadcast_provider_quota_unavailable: "Check the email provider's sending quota and run the Broadcast preflight again.",
  broadcast_provider_production_access_required: "Enable production sending with the email provider before sending this Broadcast.",
  broadcast_connection_unhealthy: "Check the email delivery connection's health and verification results in Mailrith.",
  broadcast_sender_unverified: "Verify the sender with the email provider and run the Broadcast preflight again.",
  broadcast_send_forbidden: "Check your connection permissions before starting this Broadcast.",
  broadcast_send_failed: "Run the Broadcast preflight and check its current send progress before retrying.",
  broadcast_send_not_mutable: "This Broadcast send can no longer be changed. Check its current send progress.",
  broadcast_send_missing_sender: "Select an enabled sender and run the Broadcast preflight again.",
  broadcast_send_invalid_content: "Check the Broadcast content and run its preflight again.",
  broadcast_send_invalid_audience: "Check the Broadcast's Subscriber selection and run its preflight again.",
  broadcast_send_invalid_connection: "Check the Broadcast's email delivery connection and run its preflight again.",
  broadcast_cancel_finalization_started: "The Broadcast is already finishing and cannot be canceled. Check its send progress.",
  broadcast_cancel_already_finished: "The Broadcast has already finished and cannot be canceled. Check its send progress.",
  broadcast_cancel_concurrent_update: "The Broadcast changed during cancellation. Check its current progress before retrying cancellation.",
  analytics_report_not_found: "Analytics report not found or expired.",
  authentication_required: "Sign in is required before you can authorize an app.",
  automation_activation_prerequisites_not_met: "Run the Automation preflight, resolve its blocking checks, then retry activation when it is ready.",
  automation_has_no_test_messages: "Add at least one Send Email step before sending Automation test messages.",
  automation_must_be_paused: "Pause the Automation before changing its definition.",
  automation_not_found: "Automation not found.",
  automation_run_not_found: "Automation run not found.",
  automation_test_failed: "The Automation test could not be sent. Check its steps, recipient and email delivery connection.",
  broadcast_delete_blocked: "The Broadcast cannot be deleted in its current state. Check its send progress and status before trying again.",
  broadcast_diagnostics_not_found: "Broadcast diagnostics not found.",
  broadcast_must_be_draft: "Only Broadcast drafts can be changed. Read the update operation's instructions to preserve its schedule and state while editing.",
  broadcast_not_found: "Broadcast not found.",
  broadcast_schedule_conflict: "Check the Broadcast's current status before changing its schedule.",
  broadcast_send_not_found: "Broadcast send not found.",
  broadcast_test_failed: "The Broadcast test could not be sent. Check its content, recipient and email delivery connection.",
  connection_id_required: "connection_id is required to replace credentials.",
  custom_field_in_use: "This Custom Field is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  custom_field_label_conflict: "A Custom Field with this label already exists. Choose another label.",
  custom_field_not_found: "Custom field not found.",
  custom_field_type_locked: "Custom field type changes are not available through the public API.",
  double_opt_in_preview_unavailable: "Check the Form or Landing Page's double opt-in settings before requesting a preview.",
  email_delivery_connection_in_use: "This email delivery connection is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  email_delivery_connection_missing: "Connect and enable an email sender before sending Automation test messages.",
  email_delivery_connection_not_found: "Email delivery connection not found.",
  email_delivery_connection_setup_session_not_found: "Email delivery connection setup session not found or expired.",
  email_delivery_connection_setup_session_not_renewable: "This setup session cannot be renewed. Start a new setup if it was already completed or its status record is no longer available.",
  email_delivery_connection_test_failed: "The test email could not be sent. Check the connection's verification results and test recipient in Mailrith.",
  email_delivery_connection_verification_failed: "The email delivery connection could not be verified. Check its settings and verification results in Mailrith.",
  email_delivery_provider_cannot_change: "Create a new connection to use a different email delivery provider.",
  email_starting_point_not_found: "Email starting point not found.",
  email_template_not_found: "Email template not found.",
  email_test_rate_limited: "Too many test emails. Try again later.",
  empty_update: "Provide at least one field to update.",
  expired_access_token: "The access token has expired. Run mailrith auth login to reconnect.",
  expired_api_key: "This API key has expired. Install a replacement API key.",
  form_in_use: "This Form is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  form_not_found: "Form not found.",
  form_starting_point_not_found: "Form starting point not found.",
  form_submission_not_found: "Form submission not found.",
  gdpr_consent_tag_conflict: "A GDPR consent tag for this purpose already exists.",
  insufficient_scope: "The connection needs additional permissions. Reconnect with the required permissions or install a replacement API key.",
  invalid_access_token: "Run mailrith auth login to obtain a valid access token.",
  invalid_api_key: "Install a valid API key or run mailrith auth login.",
  invalid_automation: "Check the Automation steps and fields against the operation's input schema.",
  invalid_automation_status: "Choose an Automation status allowed by the operation's input schema.",
  invalid_body: "Provide a valid JSON object using --body-file.",
  invalid_broadcast: "Check the Broadcast fields against the operation's input schema.",
  invalid_broadcast_audience_definition: "Check the Broadcast's Subscriber selection and filters.",
  invalid_broadcast_connection: "Email delivery connection is required.",
  invalid_broadcast_schedule: "Choose a valid future date and time for scheduled_at.",
  invalid_csv_text: "Check that the CSV has valid, unique column headings and correctly formatted rows.",
  invalid_cursor: "The provided starting_after cursor is invalid.",
  invalid_custom_field: "Check the Custom Field name, type and settings against the operation's input schema.",
  invalid_email_delivery_connection: "Check the email delivery connection fields. Use a setup session to replace provider credentials.",
  invalid_email_delivery_connection_setup: "Check the provider and setup fields, then start a new email delivery setup session.",
  invalid_enabled_status: "enabled must be true or false.",
  invalid_export_status: "Choose a Subscriber export status allowed by the operation's input schema.",
  invalid_form: "Check the Form fields and settings against the operation's input schema.",
  invalid_landing_page: "Check the Landing Page fields and settings against the operation's input schema.",
  invalid_magic_link: "Check the Magic Link fields against the operation's input schema.",
  invalid_mappings: "Check the CSV column mappings against the available Subscriber fields.",
  invalid_recipient: "Enter a valid recipient email address.",
  invalid_request: "Check the request fields against the operation's input schema.",
  invalid_segment: "Check the Segment fields against the operation's input schema.",
  invalid_segment_definition: "Check the Segment's filter rules against the operation's input schema.",
  invalid_sequence: "Check the Sequence fields against the operation's input schema.",
  invalid_sequence_connection: "Select an enabled email delivery connection before sending Sequence test messages.",
  invalid_sequence_operator: "Choose a sequence_operator allowed by the operation's input schema.",
  invalid_sequence_status: "Choose a Sequence status allowed by the operation's input schema.",
  invalid_setup_purpose: "purpose must be create or replace_credentials.",
  invalid_stored_email_delivery_provider_config: "The stored provider credentials are invalid. Replace this connection in Mailrith.",
  invalid_subscriber_email: "Enter a valid Subscriber email address.",
  invalid_subscriber_status: "Choose a Subscriber status allowed by the operation's input schema.",
  invalid_tag_name: "Enter a valid Tag name.",
  invalid_tag_operator: "Use has_any_of or has_none_of for tag_operator.",
  invalid_template_body: "Check the email Template content against the operation's input schema.",
  invalid_template_enabled: "Email template enabled must be true or false.",
  invalid_template_name: "Enter a valid email Template name.",
  invalid_test_message_ids: "Choose message IDs that belong to this Sequence or Automation.",
  invalid_test_recipient: "Enter a valid email address for the test recipient.",
  invalid_webhook_event_patterns: "Choose event patterns supported by Outbound Webhooks.",
  invalid_webhook_subscription_name: "Enter a valid Outbound Webhook name.",
  invalid_webhook_subscription_status: "Choose an Outbound Webhook status allowed by the operation's input schema.",
  invalid_webhook_subscription_url: "Enter a valid public HTTPS URL for the Outbound Webhook.",
  landing_page_not_found: "Landing page not found.",
  landing_page_starting_point_not_found: "Landing Page starting point not found.",
  landing_page_submission_not_found: "Landing Page submission not found.",
  magic_link_in_use: "This Magic Link is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  magic_link_name_conflict: "Magic link name already exists.",
  magic_link_not_found: "Magic link not found.",
  method_not_allowed: "This action does not support the requested method. Check the operation's description.",
  not_found: "Route not found.",
  owner_suspended: "The workspace owner's account is suspended. Contact Mailrith support.",
  pro_plan_required: "Mailrith Pro is required to use this Public API feature.",
  rate_limited: "Too many API write requests. Try again later.",
  removed_tag_double_opt_in_fields: "Configure double opt-in on Forms and Landing Pages. Remove double opt-in fields from the Tag request.",
  request_body_too_large: "Reduce the request body size before trying again.",
  revoked_access_token: "The access token has been revoked. Run mailrith auth login to reconnect.",
  revoked_api_key: "This API key has been revoked. Install a replacement API key.",
  secure_setup_session_required: "Provider credentials can only be replaced through an email delivery connection setup session.",
  segment_in_use: "This Segment is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  segment_name_conflict: "Segment name already exists.",
  segment_not_found: "Segment not found.",
  sender_identity_not_found: "Sender identity not found.",
  separate_automation_status_action_required: "Use the Automation status endpoint to activate, pause, or return an Automation to draft.",
  separate_broadcast_send_action_required: "Create or update the Broadcast draft first, then use the separate send or schedule operation.",
  separate_sequence_status_action_required: "Use the Sequence status endpoint to activate or pause a Sequence.",
  sequence_access_required: "This action requires access to Sequences. Check your plan and connection permissions.",
  sequence_activation_prerequisites_not_met: "Run the Sequence preflight, resolve its blocking checks, then retry activation when it is ready.",
  sequence_has_no_test_messages: "Add at least one email before sending Sequence test messages.",
  sequence_in_use: "This Sequence is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  sequence_must_be_paused: "Pause the Sequence before changing its content or delivery settings.",
  sequence_not_found: "Sequence not found.",
  sequence_test_failed: "The Sequence test could not be sent. Check its messages, recipient and email delivery connection.",
  shared_custom_field: "Shared custom fields cannot be deleted through a workspace API key.",
  shared_email_delivery_connection_requires_ui: "This connection is shared with another workspace. Manage it in Mailrith.",
  shared_email_template: "Shared email templates cannot be deleted through a workspace API key.",
  starting_point_content_conflict: "Provide starting_point_id or custom content, not both.",
  subscriber_conflict: "The Subscriber change conflicts with existing data. Retrieve the Subscriber's current state before trying again.",
  subscriber_export_job_not_found: "Subscriber export job not found.",
  subscriber_import_job_not_found: "Subscriber import job not found.",
  subscriber_import_upload_missing: "The uploaded CSV is unavailable. Start a new upload and ask the user to choose the file again.",
  subscriber_import_upload_not_found: "Subscriber import upload not found or expired. Start a new upload and ask the user to choose the CSV file in Mailrith.",
  subscriber_import_upload_not_ready: "The CSV upload is not ready. Ask the user to finish the browser upload, then check the upload again.",
  subscriber_not_found: "Subscriber not found.",
  subscriber_required: "Provide the Subscriber ID required for this operation.",
  tag_in_use: "This Tag is used by other resources. Review its references in Mailrith and remove or update them before retrying.",
  tag_name_conflict: "Tag name already exists.",
  tag_not_found: "Tag not found.",
  too_many_sequence_filters: "Reduce the number of Sequence filters and try again.",
  too_many_tag_filters: "Reduce the number of Tag filters and try again.",
  trial_checkout_required: "Start your Mailrith trial before using this workspace.",
  webhook_subscription_limit_exceeded: "The workspace has reached its Outbound Webhook limit. Remove an unused subscription before creating another.",
  webhook_subscription_name_conflict: "A webhook subscription with this name already exists in the workspace.",
  webhook_subscription_not_found: "Webhook subscription not found.",
  workspace_not_found: "Workspace not found.",
  workspace_plan_limit_exceeded: "This workspace is over your current plan limit. You can view, export, or delete existing data, but cannot create or edit records until the workspace is within your plan limit.",
  wrong_resource: "This access token belongs to a different Mailrith service. Run mailrith auth login for the CLI.",
};

// Exact matches to reviewed, static validation messages can retain the field
// explanation even when the API uses a broad code such as invalid_request.
// Never match substrings or interpolate a server-provided value.
const validationMessages = new Map([
  "A form with this name already exists in this workspace.",
  "A landing page with this name or slug already exists in this workspace.",
  "A published form must include an email field.",
  "A sequence with this name already exists in this workspace.",
  "Add at least one option for dropdown, single select, or multi select fields.",
  "Automation name is required.",
  "Automation status is invalid.",
  "Automation status is required.",
  "Body is required.",
  "Broadcast not found.",
  "Broadcast status is invalid.",
  "Broadcast status is required.",
  "CSV file does not contain any rows.",
  "CSV file must include headers and at least one data row.",
  "CSV must include a \"Name\" column.",
  "Choose whether each sequence is added or removed. The same sequence cannot be in both lists.",
  "Choose whether each tag is added or removed. The same tag cannot be in both lists.",
  "Complete the Automation definition before Mailrith checks its referenced resources.",
  "Connect a landing page domain before setting a custom landing page slug.",
  "Connection is not linked to this workspace.",
  "Country filters must include at least one country.",
  "Current segment is invalid.",
  "Custom field filters must include a single value.",
  "Custom field label is required.",
  "Custom field label must not match Subscriber Name or Subscriber Email.",
  "Custom field type is invalid.",
  "Custom field type is required.",
  "Custom landing page slugs require Mailrith Pro.",
  "Custom slug must be 2-80 URL-safe characters.",
  "Destination URL is required.",
  "Destination URL must be a valid http or https URL.",
  "Email body is required.",
  "Email delivery connection is required to enable a sequence.",
  "Email delivery connection is required.",
  "Email field must be mapped to a CSV column.",
  "Form fields must be saved inside the builder form block, not definition.fields.",
  "Form name is required.",
  "Form not found",
  "Form requests may only include name and definition.",
  "Form styles must be saved inside definition.builder, not as top-level styles.",
  "Form styles must be saved inside definition.builder, not definition.styles.",
  "Form success messages cannot include form blocks.",
  "Forms can only include each custom field once.",
  "Forms can only include one builder form block.",
  "Forms can only include one email field.",
  "Forms must be created with the builder.",
  "Forms must include a builder form block.",
  "Landing page could not be created.",
  "Landing page custom CSS contains unsupported rules.",
  "Landing page custom CSS must be 12,000 characters or fewer.",
  "Landing page custom CSS must be text.",
  "Landing page custom slug already exists in this workspace.",
  "Landing page definition includes an unsupported block.",
  "Landing page definition must be an object.",
  "Landing page definition must include blocks.",
  "Landing page form redirect URL is required.",
  "Landing page form redirect URLs must be valid public URLs.",
  "Landing page name is required.",
  "Landing page not found.",
  "Landing page slug already exists in this workspace.",
  "Landing page slug must be 2-80 URL-safe characters.",
  "Landing page social image asset is invalid.",
  "Landing page social image must be a valid public URL.",
  "Landing page success page definition includes an unsupported block.",
  "Landing page success page definition must include blocks.",
  "Magic Link destination type must be redirect or message.",
  "Magic Link name already exists.",
  "Magic Link name is required.",
  "Mailrith Pro is required to use custom fields in forms.",
  "Mailrith Pro is required to use custom fields in landing page forms.",
  "Number custom field filters must include a valid number.",
  "One or more custom fields are invalid.",
  "One or more custom fields are not available in this workspace.",
  "One or more forms are invalid.",
  "One or more import rows are no longer available.",
  "One or more landing page form custom fields are unavailable.",
  "One or more landing page form tags are unavailable.",
  "One or more magic links are invalid.",
  "One or more mapped custom fields are no longer available.",
  "One or more segments are invalid.",
  "One or more selected sequences were not found or are not published.",
  "One or more selected tags were not found.",
  "One or more sequences are invalid.",
  "One or more sequences were not found.",
  "One or more tags are invalid.",
  "One or more tags are not available in this workspace.",
  "One or more tags were not found.",
  "One or more workspaces were not found.",
  "Publish at least one email before enabling this sequence.",
  "Redirect URL must be a valid http or https URL.",
  "Remove from Automation actions must target another automation. Use Exit this Automation to end the current automation.",
  "Reply-To email must be valid.",
  "Scheduled date is required.",
  "Scheduled date must be in the future.",
  "Segment id must be a string.",
  "Segment name is required.",
  "Segments cannot reference themselves or create circular references.",
  "Select at least one sequence.",
  "Select at least one subscriber.",
  "Select at least one tag.",
  "Select at least one webhook event pattern.",
  "Select at least one workspace.",
  "Sequence name is required.",
  "Sequence not found",
  "Start Automation actions cannot create a loop between automations.",
  "Subject is required.",
  "Subscribed on date is required.",
  "Subscriber country must be a valid country code or country name.",
  "Subscriber custom field values are invalid.",
  "Subscriber email is required.",
  "Subscriber email must be valid.",
  "Subscriber name is required.",
  "Subscriber status filters can include only one status.",
  "Subscriber status filters include an unsupported status.",
  "Subscriber status is invalid.",
  "Subscriber status is required.",
  "Tag name is required.",
  "Template body is required.",
  "Template body is too large. Shorten the email or remove extra formatting.",
  "Template name is required.",
  "The provided Magic Link cursor is invalid.",
  "Upload at least one tag row to import.",
  "Verify the landing page domain before setting a custom landing page slug.",
  "Webhook event patterns must be an array.",
  "Webhook subscription name is required.",
  "Webhook subscription name must be 80 characters or fewer.",
  "Webhook subscription status is invalid.",
  "Workspace not found.",
  "Connection name is required.",
  "From name is required.",
  "Email delivery provider is required.",
  "Email delivery provider is not supported.",
  "Email delivery connection is disabled.",
  "Request body is required.",
  "Request body must be a JSON object.",
  "Request body must be valid JSON.",
].map((message) => [message, message]));

export const describeMailrithApiError = (
  status: number, code: unknown, message?: unknown,
) => {
  if (
    status >= 400 && status < 500 && status !== 408 &&
    typeof code === "string" && code.length <= 128 &&
    Object.hasOwn(apiErrorMessages, code)
  ) {
    const validationMessage = [400, 409, 422].includes(status) &&
      typeof message === "string" && message.length <= 512
      ? validationMessages.get(message)
      : undefined;
    return { code, message: validationMessage ?? apiErrorMessages[code]! };
  }
  switch (status) {
    case 401:
      return { code: "api_authentication_failed", message: "Authentication failed. Run mailrith auth login or install a valid API key." };
    case 403:
      return { code: "api_permission_denied", message: "Access was denied. Check the connection's permissions and your workspace plan." };
    case 404:
      return { code: "api_resource_not_found", message: "The resource was not found. Check its ID and the connected workspace." };
    case 409:
      return { code: "api_conflict", message: "The request conflicts with the resource's current state. Retrieve it again and review its status before retrying." };
    case 429:
      return { code: "api_rate_limited", message: "Too many requests. Wait before trying again." };
    default:
      if (status >= 500 || status === 408) {
        return { code: "api_temporarily_unavailable", message: "Mailrith is temporarily unavailable. Check the result of any changes before retrying with the same idempotency key." };
      }
      return { code: "api_request_failed", message: `Mailrith rejected the request (HTTP ${status}). Check the operation's input schema and request fields.` };
  }
};
